### ISSUE TITLE
12 hour format - 0am vs 12pm

### ISSUE THREAD

**Issue by JJBNY** [jacquesCedric/MMM-darksky-hourly#2]
thanks for the awesome module!  one nit - when using am/pm time the display shows 0am instead of 12pm
![time](https://user-images.githubusercontent.com/41481773/43009304-4b8bf66a-8c0b-11e8-8e03-91114e5920e9.JPG)

**Comment by tstern27** [comment]
I am having this issue as well. Have you discovered any fix to it? Otherwise I love this module!

**Comment by mattdb** [comment]
This was fixed by #5, which has now been merged into master. Suggest that this issue can be closed.
