### ISSUE TITLE
how can i change font color?

### ISSUE THREAD

**Issue by JooMiHyun** [jacquesCedric/MMM-darksky-hourly#3]
in MMM-darksky-hourly.css

**Comment by Ben4x4** [comment]
Hi, How do i change the font size of the text and icons in hourly table? If it's in MMM-darksky-hourly.css where abouts is it? Thanks.

**Comment by jacquesCedric** [comment]
It's been a long time since I've had a look at this project, but I think you just need to add a tiny bit of custom CSS to the `MMM-darksky-hourly.css` file.

See below, but replace COLOUR with whatever colours you like. 
```
.MMM-darksky-hourly { color: #COLOUR; }

.MMM-darksky-hourly .dark { color: #COLOUR; }

.MMM-darksky-hourly .darker { color: #COLOUR; }
```

Also, sorry about the late reply.
